// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package devices;

public interface LengthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.LengthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   * @return The length.
   */
  int getLength();
}
