// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package devices;

public interface MultiStringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.MultiStringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .printer.StringRequest multiresponse = 1;</code>
   */
  java.util.List<devices.StringRequest> 
      getMultiresponseList();
  /**
   * <code>repeated .printer.StringRequest multiresponse = 1;</code>
   */
  devices.StringRequest getMultiresponse(int index);
  /**
   * <code>repeated .printer.StringRequest multiresponse = 1;</code>
   */
  int getMultiresponseCount();
  /**
   * <code>repeated .printer.StringRequest multiresponse = 1;</code>
   */
  java.util.List<? extends devices.StringRequestOrBuilder> 
      getMultiresponseOrBuilderList();
  /**
   * <code>repeated .printer.StringRequest multiresponse = 1;</code>
   */
  devices.StringRequestOrBuilder getMultiresponseOrBuilder(
      int index);
}
