// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package devices;

public final class PrinterServiceImpl {
  private PrinterServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_LengthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_LengthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_ReplaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_ReplaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_MultiStringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_MultiStringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_printer_MultiStringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_printer_MultiStringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprinter.proto\022\007printer\" \n\016LengthRespon" +
      "se\022\016\n\006length\030\001 \001(\005\",\n\016ReplaceRequest\022\014\n\004" +
      "text\030\001 \001(\t\022\014\n\004char\030\002 \001(\t\"\034\n\rStringReques" +
      "t\022\013\n\003val\030\001 \001(\t\"\035\n\016StringResponse\022\013\n\003val\030" +
      "\001 \001(\t\"\"\n\022MultiStringRequest\022\014\n\004text\030\001 \003(" +
      "\t\"D\n\023MultiStringResponse\022-\n\rmultirespons" +
      "e\030\001 \003(\0132\026.printer.StringRequest2\214\002\n\016Prin" +
      "terService\022;\n\006turnOn\022\026.printer.StringReq" +
      "uest\032\027.printer.StringResponse\"\000\022<\n\007turnO" +
      "ff\022\026.printer.StringRequest\032\027.printer.Str" +
      "ingResponse\"\000\022>\n\tgetStatus\022\026.printer.Str" +
      "ingRequest\032\027.printer.StringResponse\"\000\022?\n" +
      "\005Print\022\033.printer.MultiStringRequest\032\027.pr" +
      "inter.StringResponse\"\000B\'\n\017devices.printe" +
      "rB\022PrinterServiceImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_printer_LengthResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_printer_LengthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_LengthResponse_descriptor,
        new java.lang.String[] { "Length", });
    internal_static_printer_ReplaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_printer_ReplaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_ReplaceRequest_descriptor,
        new java.lang.String[] { "Text", "Char", });
    internal_static_printer_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_printer_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_StringRequest_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_printer_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_printer_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_StringResponse_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_printer_MultiStringRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_printer_MultiStringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_MultiStringRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_printer_MultiStringResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_printer_MultiStringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_printer_MultiStringResponse_descriptor,
        new java.lang.String[] { "Multiresponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
