// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package devices;

public interface ReplaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.ReplaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>string char = 2;</code>
   * @return The char.
   */
  java.lang.String getChar();
  /**
   * <code>string char = 2;</code>
   * @return The bytes for char.
   */
  com.google.protobuf.ByteString
      getCharBytes();
}
