// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package devices;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:printer.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   * @return The val.
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   * @return The bytes for val.
   */
  com.google.protobuf.ByteString
      getValBytes();
}
